<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Veena" name="com.acktinos.tests.ITILUserTests" tests="1" failures="0" timestamp="20 May 2018 09:24:20 GMT" time="0.209" errors="1">
  <testcase name="doReportSetup" time="0.209" classname="com.acktinos.tests.ITILUserTests">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerExceptionat javassist.bytecode.Utf8Info.hashCode(ConstPool.java:1872)at java.util.HashMap.hash(HashMap.java:339)at java.util.HashMap.get(HashMap.java:557)at javassist.bytecode.ConstPool.addItem(ConstPool.java:854)at javassist.bytecode.ConstPool.addUtf8Info(ConstPool.java:1110)at javassist.bytecode.AttributeInfo.<init>(AttributeInfo.java:62)at javassist.bytecode.AnnotationsAttribute.<init>(AnnotationsAttribute.java:126)at javassist.bytecode.AnnotationsAttribute.<init>(AnnotationsAttribute.java:141)at com.acktinos.tests.CommonTest.addXmlRootAnnotationDynamicly(CommonTest.java:119)at com.acktinos.tests.CommonTest.doReportSetup(CommonTest.java:81)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:451)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)at org.testng.TestRunner.beforeRun(TestRunner.java:529)at org.testng.TestRunner.run(TestRunner.java:497)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </error>
  </testcase> <!-- doReportSetup -->
</testsuite> <!-- com.acktinos.tests.ITILUserTests -->
